version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - ui/node_modules

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
